#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, os, pathlib, shlex, subprocess, sys
from datetime import datetime, timezone

HERE = pathlib.Path(__file__).resolve().parent


def run_python(script: str, args: list[str]) -> int:
    cmd = [sys.executable, str(HERE / script)] + [str(a) for a in args]
    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if proc.stdout:
        print(proc.stdout.rstrip())
    return proc.returncode

def load_json(path: pathlib.Path) -> dict:
    return json.loads(path.read_text(encoding='utf-8'))

def write_text(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8', newline='\n')

def taskrun_dir(taskrun_path: pathlib.Path) -> pathlib.Path:
    return taskrun_path.resolve().parent

def cmd_start(args) -> int:
    return run_python('projectgate_task_start.py', ['--project-pack', args.project_pack, '--task-type', args.task_type, '--task-title', args.task_title, '-p', args.profile, '--run-root', args.run_root])

def cmd_stage(args) -> int:
    return run_python('projectgate_stage_gate.py', ['--taskrun', args.taskrun, '--stage', args.stage, '--input', args.input])

def cmd_delivery(args) -> int:
    return run_python('projectgate_delivery_check.py', ['--taskrun', args.taskrun])

def cmd_observe(args) -> int:
    return run_python('projectgate_observation_gate.py', ['--taskrun', args.taskrun, '--input', args.input])

def cmd_continuity(args) -> int:
    return run_python('projectgate_taskrun_continuity_gate.py', ['--taskrun', args.taskrun, '--input', args.input])

def cmd_candidates(args) -> int:
    forwarded = ['--project-pack', args.project_pack, args.candidate_cmd]
    if args.candidate_cmd == 'list':
        pass
    elif args.candidate_cmd == 'show':
        forwarded.append(args.id)
        if args.kind: forwarded += ['--kind', args.kind]
    elif args.candidate_cmd == 'approve':
        forwarded.append(args.id)
        if args.kind: forwarded += ['--kind', args.kind]
        if args.owner_approved: forwarded.append('--owner-approved')
        if args.reason: forwarded += ['--reason', args.reason]
    elif args.candidate_cmd == 'reject':
        forwarded.append(args.id)
        if args.kind: forwarded += ['--kind', args.kind]
        if args.reason: forwarded += ['--reason', args.reason]
    elif args.candidate_cmd == 'merge':
        forwarded.append(args.source)
        forwarded += ['--into', args.target]
        if args.kind: forwarded += ['--kind', args.kind]
        if args.reason: forwarded += ['--reason', args.reason]
    else:
        print('RESULT=FAIL')
        print('FAILED_STAGE=CLI')
        print('FAIL_REASON=unknown candidates command')
        return 1
    return run_python('projectgate_candidate_lifecycle.py', forwarded)

def cmd_pack(args) -> int:
    forwarded = [args.pack_cmd]
    if args.pack_cmd in {'info', 'validate'}:
        forwarded += ['--project-pack', args.project_pack]
    elif args.pack_cmd == 'export':
        forwarded += ['--project-pack', args.project_pack, '--out', args.out]
    elif args.pack_cmd == 'install':
        forwarded += ['--project-pack', args.project_pack, '--dest', args.dest]
        if args.dry_run: forwarded.append('--dry-run')
        if args.force: forwarded.append('--force')
    else:
        print('RESULT=FAIL')
        print('FAILED_STAGE=CLI')
        print('FAIL_REASON=unknown pack command')
        return 1
    return run_python('projectgate_pack_manager.py', forwarded)

def cmd_status(args) -> int:
    code = 0
    if args.project_pack:
        code = run_python('projectgate_pack_manager.py', ['info', '--project-pack', args.project_pack])
    if args.taskrun:
        try:
            taskrun = load_json(pathlib.Path(args.taskrun))
            print('TASKRUN=' + str(pathlib.Path(args.taskrun).resolve()))
            print('TASKRUN_STAGE=' + str(taskrun.get('stage', '')))
            print('GATE_HISTORY_COUNT=' + str(len(taskrun.get('gateHistory') or [])))
            print('AUTO_CAPTURED_INCIDENTS=' + str(len(taskrun.get('autoCapturedIncidents') or [])))
            print('AUTO_KNOWN_BUG_CANDIDATES=' + str(len(taskrun.get('autoGeneratedKnownBugRuleCandidates') or [])))
            print('AUTO_SOP_CANDIDATES=' + str(len(taskrun.get('autoGeneratedSOPCandidates') or [])))
        except Exception as exc:
            print('RESULT=FAIL')
            print('FAILED_STAGE=CLI_STATUS')
            print('FAIL_REASON=' + str(exc))
            return 1
    return code

def cmd_exec(args) -> int:
    taskrun_path = pathlib.Path(args.taskrun).resolve()
    if not taskrun_path.exists():
        print('RESULT=FAIL')
        print('FAILED_STAGE=CLI_EXEC')
        print('FAIL_REASON=taskrun missing: ' + str(taskrun_path))
        return 1
    if not args.command:
        print('RESULT=FAIL')
        print('FAILED_STAGE=CLI_EXEC')
        print('FAIL_REASON=no command supplied after --')
        return 1
    cmd = args.command
    if cmd and cmd[0] == '--':
        cmd = cmd[1:]
    ts = datetime.now().strftime('%Y%m%d_%H%M%S_%f')
    log = taskrun_dir(taskrun_path) / f'pg_exec_{ts}.txt'
    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=False, cwd=args.cwd or None)
    text = []
    text.append('PG_EXEC_UTC=' + datetime.now(timezone.utc).isoformat())
    text.append('COMMAND=' + ' '.join(shlex.quote(x) for x in cmd))
    text.append('EXIT_CODE=' + str(proc.returncode))
    text.append('STDOUT_BEGIN')
    text.append(proc.stdout or '')
    text.append('STDOUT_END')
    text.append('STDERR_BEGIN')
    text.append(proc.stderr or '')
    text.append('STDERR_END')
    write_text(log, '\n'.join(text))
    print('RESULT=PASS' if proc.returncode == 0 else 'RESULT=FAIL')
    print('PG_EXEC_LOG=' + str(log))
    print('PG_EXEC_EXIT_CODE=' + str(proc.returncode))
    obs_code = run_python('projectgate_observation_gate.py', ['--taskrun', str(taskrun_path), '--input', str(log)])
    if proc.returncode != 0:
        return proc.returncode if proc.returncode < 128 else 1
    return obs_code

def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(prog='pg', description='ProjectGate command line wrapper.')
    sub = ap.add_subparsers(dest='cmd', required=True)
    st = sub.add_parser('start'); st.add_argument('--project-pack', required=True); st.add_argument('--task-type', required=True); st.add_argument('--task-title', required=True); st.add_argument('-p','--profile', default='L'); st.add_argument('--run-root', required=True)
    sg = sub.add_parser('stage'); sg.add_argument('--taskrun', required=True); sg.add_argument('--stage', required=True); sg.add_argument('--input', required=True)
    de = sub.add_parser('delivery'); de.add_argument('--taskrun', required=True)
    ob = sub.add_parser('observe'); ob.add_argument('--taskrun', required=True); ob.add_argument('--input', required=True)
    co = sub.add_parser('continuity'); co.add_argument('--taskrun', required=True); co.add_argument('--input', required=True)
    ex = sub.add_parser('exec'); ex.add_argument('--taskrun', required=True); ex.add_argument('--cwd', default=''); ex.add_argument('command', nargs=argparse.REMAINDER)
    stat = sub.add_parser('status'); stat.add_argument('--project-pack', default=''); stat.add_argument('--taskrun', default='')
    cand = sub.add_parser('candidates'); cand.add_argument('--project-pack', required=True); cs = cand.add_subparsers(dest='candidate_cmd', required=True)
    cs.add_parser('list')
    cshow=cs.add_parser('show'); cshow.add_argument('id'); cshow.add_argument('--kind', choices=['sop','knownbug'])
    cap=cs.add_parser('approve'); cap.add_argument('id'); cap.add_argument('--kind', choices=['sop','knownbug']); cap.add_argument('--owner-approved', action='store_true'); cap.add_argument('--reason', default='')
    crej=cs.add_parser('reject'); crej.add_argument('id'); crej.add_argument('--kind', choices=['sop','knownbug']); crej.add_argument('--reason', default='')
    cm=cs.add_parser('merge'); cm.add_argument('source'); cm.add_argument('--into', dest='target', required=True); cm.add_argument('--kind', choices=['sop','knownbug']); cm.add_argument('--reason', default='')
    pack=sub.add_parser('pack'); ps=pack.add_subparsers(dest='pack_cmd', required=True)
    for n in ['info','validate']:
        sp=ps.add_parser(n); sp.add_argument('--project-pack', required=True)
    pex=ps.add_parser('export'); pex.add_argument('--project-pack', required=True); pex.add_argument('--out', required=True)
    pin=ps.add_parser('install'); pin.add_argument('--project-pack', required=True); pin.add_argument('--dest', required=True); pin.add_argument('--dry-run', action='store_true'); pin.add_argument('--force', action='store_true')
    return ap

def main() -> int:
    args = build_parser().parse_args()
    if args.cmd == 'start': return cmd_start(args)
    if args.cmd == 'stage': return cmd_stage(args)
    if args.cmd == 'delivery': return cmd_delivery(args)
    if args.cmd == 'observe': return cmd_observe(args)
    if args.cmd == 'continuity': return cmd_continuity(args)
    if args.cmd == 'exec': return cmd_exec(args)
    if args.cmd == 'status': return cmd_status(args)
    if args.cmd == 'candidates': return cmd_candidates(args)
    if args.cmd == 'pack': return cmd_pack(args)
    print('RESULT=FAIL')
    print('FAILED_STAGE=CLI')
    print('FAIL_REASON=unknown command')
    return 1

if __name__ == '__main__':
    raise SystemExit(main())
