#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, pathlib, re, shutil
from datetime import datetime, timezone

SAFE_RE = re.compile(r'[^A-Za-z0-9_.-]+')


def safe(text: str) -> str:
    return SAFE_RE.sub('_', text.strip())[:80].strip('_') or 'project'


def iter_docs(root: pathlib.Path):
    for p in sorted(root.rglob('*')):
        if p.is_file() and p.suffix.lower() in {'.md', '.txt', '.json'}:
            yield p


def main() -> int:
    ap = argparse.ArgumentParser(description='Compile project documents into a candidate Project Pack. This is a deterministic scaffold, not final approval.')
    ap.add_argument('--project-name', required=True)
    ap.add_argument('--project-root', required=True)
    ap.add_argument('--docs-dir', required=True)
    ap.add_argument('--out-pack', required=True)
    ap.add_argument('--default-budget', default='low', choices=['low', 'medium', 'high'])
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()
    docs = pathlib.Path(args.docs_dir).resolve()
    out = pathlib.Path(args.out_pack).resolve()
    if not docs.exists():
        print('RESULT=FAIL')
        print('FAILED_STAGE=COMPILE_PACK')
        print('FAIL_REASON=docs dir missing')
        return 1
    doc_files = list(iter_docs(docs))
    if args.dry_run:
        print('RESULT=PASS')
        print('DRY_RUN=PASS')
        print('DOC_FILE_COUNT=' + str(len(doc_files)))
        print('OUT_PACK=' + str(out))
        return 0
    for sub in ['SOPs/candidates', 'SOPs/active', 'KnownBugRules/candidates', 'KnownBugRules/active', 'TaskTypes/candidates', 'TaskTypes/active', 'EvidenceProfiles', 'rules', 'docs_source']:
        (out / sub).mkdir(parents=True, exist_ok=True)
    manifest = {
        'schema': 'projectgate_project_pack_v0_1',
        'created_utc': datetime.now(timezone.utc).isoformat(),
        'projectId': safe(args.project_name).lower(),
        'projectName': args.project_name,
        'projectRoot': str(pathlib.Path(args.project_root).resolve()),
        'packVersion': '0.1.0',
        'defaultBudget': args.default_budget,
        'sourceDocs': [str(p.relative_to(docs)) for p in doc_files]
    }
    (out / 'project_manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8', newline='\n')
    (out / 'AGENTS.md.template').write_text(f'''# {args.project_name} ProjectGate Instructions\n\nThis project uses ProjectGate.\n\n## Always-on rules\n\n- Start ambiguous or high-risk tasks with read-only audit.\n- Do not guess.\n- Missing facts stop progress or trigger read-only fact collection.\n- Destructive actions require explicit owner authorization.\n- Follow active SOPs and known bug rules from this Project Pack.\n\n## Project Pack\n\nProject name: {args.project_name}\nDefault budget: {args.default_budget}\n''', encoding='utf-8', newline='\n')
    (out / 'README_ProjectPack.md').write_text(f'''# {args.project_name} Project Pack\n\nGenerated by ProjectGate Core v0.1.\n\nThis pack is a candidate scaffold. Review and promote candidates before treating them as active rules.\n''', encoding='utf-8', newline='\n')
    for p in doc_files:
        shutil.copy2(p, out / 'docs_source' / p.name)
        candidate = out / 'SOPs' / 'candidates' / (safe(p.stem) + '_candidate.md')
        candidate.write_text(f'''# SOP Candidate from {p.name}\n\nStatus: candidate\nSource: `{p.name}`\n\nReview this document and convert it into a structured SOP if reusable.\n''', encoding='utf-8', newline='\n')
    print('RESULT=PASS')
    print('PROJECT_PACK=' + str(out))
    print('DOC_FILE_COUNT=' + str(len(doc_files)))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
